apiVersion: v1
kind: Service
metadata:
  name: goserver-service
spec:
  selector:
    app: goserver
  type: LoadBalancer
  ports:
    - name: goserver-service-port
      port: 8000
      protocol: TCP
      targetPort: 80
      
       